# Generated by Django 3.2.9 on 2021-11-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VetApps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='a_birthdate',
            new_name='animalBirthdate',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='a_created_at',
            new_name='animalCreated',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='a_customer',
            new_name='animalCustomer',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='a_kind',
            new_name='animalKind',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='a_name',
            new_name='animalName',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='a_photo',
            new_name='animalPhoto',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='a_updated_at',
            new_name='animalUpdated',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_address',
            new_name='customerAddress',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_city',
            new_name='customerCity',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_created_at',
            new_name='customerCreated',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_name',
            new_name='customerName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_phone',
            new_name='customerPhone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_photo',
            new_name='customerPhoto',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_updated_at',
            new_name='customerUpdated',
        ),
        migrations.RenameField(
            model_name='kind',
            old_name='c_created_at',
            new_name='kindCreated',
        ),
        migrations.RenameField(
            model_name='kind',
            old_name='c_updated_at',
            new_name='kindUpdated',
        ),
    ]
