# Generated by Django 3.2.9 on 2021-11-10 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VetApps', '0002_auto_20211110_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animalCustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Animals', to='VetApps.customer'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalKind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Animals', to='VetApps.kind'),
        ),
    ]
